# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-06-27 09:58:05
"""
import arcpy
from sys import argv

def Model(Home_fire_fatalities_in_the_news="Home fire fatalities in the news", _2016_2020_Population_Variables_County="ACS Population Variables - Boundaries\\County"):  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Analysis Tools.tbx.tbx")
    Expression = "Date >= timestamp '2016-01-01 12:37:06' And Date <= timestamp '2020-12-31 12:37:38'"

    # Process: Make Feature Layer (Make Feature Layer) (management)
    HFF_2016_2020 = "021211_Layer"
    arcpy.management.MakeFeatureLayer(in_features=Home_fire_fatalities_in_the_news, out_layer=HFF_2016_2020, where_clause=Expression, workspace="", field_info="Date Date VISIBLE NONE;State State VISIBLE NONE;City City VISIBLE NONE;Cause Cause VISIBLE NONE;Description Description VISIBLE NONE;Gender Gender VISIBLE NONE;Age Age VISIBLE NONE;Age_demographic Age_demographic VISIBLE NONE;MFI MFI VISIBLE NONE;Disability Disability VISIBLE NONE;Residential_building_type Residential_building_type VISIBLE NONE;Smoke_alarms Smoke_alarms VISIBLE NONE;Media_URL Media_URL VISIBLE NONE;FID FID VISIBLE NONE;Shape Shape VISIBLE NONE")

    # Process: Summarize Within (Summarize Within) (analysis)
    Counties_w_Summarized_HFF = "C:\\Users\\mic12213\\OneDrive - Esri\\Documents\\ArcGIS\\Projects\\US_Fire_Admin_FEMA\\US_Fire_Admin_FEMA.gdb\\County_Population_HFF_Summarized"
    Output_Grouped_Table = ""
    arcpy.analysis.SummarizeWithin(in_polygons=_2016_2020_Population_Variables_County, in_sum_features=HFF_2016_2020, out_feature_class=Counties_w_Summarized_HFF, keep_all_polygons="KEEP_ALL", sum_fields=[], sum_shape="ADD_SHAPE_SUM", shape_unit="", group_field="", add_min_maj="NO_MIN_MAJ", add_group_percent="NO_PERCENT", out_group_table=Output_Grouped_Table)

    # Process: Add Field (Add Field) (management)
    County_Population_HFF_Summarized = arcpy.management.AddField(in_table=Counties_w_Summarized_HFF, field_name="Fatalities_per_100000", field_type="DOUBLE", field_precision=None, field_scale=None, field_length=None, field_alias="Fatalities Per 100,000", field_is_nullable="NULLABLE", field_is_required="NON_REQUIRED", field_domain="")[0]

    # Process: Calculate Field (Calculate Field) (management)
    County_Population_HFF_Summarized_3_ = arcpy.management.CalculateField(in_table=County_Population_HFF_Summarized, field="Fatalities_per_100000", expression="(!Point_Count!/!B01001_001E!)*100000", expression_type="PYTHON3", code_block="", field_type="DOUBLE", enforce_domains="NO_ENFORCE_DOMAINS")[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\mic12213\OneDrive - Esri\Documents\ArcGIS\Projects\US_Fire_Admin_FEMA\US_Fire_Admin_FEMA.gdb", workspace=r"C:\Users\mic12213\OneDrive - Esri\Documents\ArcGIS\Projects\US_Fire_Admin_FEMA\US_Fire_Admin_FEMA.gdb"):
        Model(*argv[1:])
